- name: create directory for each keypair
  file:
    path: "{{ admin_path }}/jumpbox_keys/{{ user_name }}"
    state: directory
- name: populate key filesystem with keypairs
  openssh_keypair:
    path: "{{ admin_path }}/jumpbox_keys/{{ user_name }}/id_rsa"
