- name: create directory for each keypair
  file:
    path: "{{ root_dir }}/admin/jumpbox_keys/{{ user_name }}"
    state: directory
- name: populate key filesystem with keypairs
  openssh_keypair:
    path: "{{ root_dir }}/admin/jumpbox_keys/{{ user_name }}/id_rsa"
