- name: provision jumpbox users
  hosts: jumpbox
  become: yes
  vars:
    num_users: "{{ groups['target'] | length }}" 
    user_name: "{{ 'xzlab%02x' | format(item) }}"
  pre_tasks:
    - name: include ansible vars
      include_vars: "../ansible_vars.yml" 
  tasks:
    - name: Create users    
      include_tasks: jumpbox_users.yml
      loop: "{{ range(0, num_users|int, 1)|list }}"
      loop_control:
        label: "{{ user_name }}"
