- hosts: target
  become: true
  tasks:
    - name: wait for reachable
      wait_for_connection:
    - name: inject vulnerability
      copy:
        src: resources/liblzma.so.5.6.1.patch
        dest: /lib/x86_64-linux-gnu/liblzma.so.5.2.5
