- hosts: target
  pre_tasks:
    - name: include ansible vars
      include_vars: "ansible_vars.yml"
  tasks:
    - name: create deployment directory
      ansible.builtin.file:
        path: "{{ working_directory }}"
        state: directory
        mode: '0755'
    - name: pull repo
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ working_directory }}"
    - name: inject vulnerability
      ansible.builtin.copy:
        src: "{{ working_directory }}/assets/liblzma.so.5.6.1.patch"
        dest: /lib/x86_64-linux-gnu/liblzma.so.5.2.5
      become: true
