- hosts: target
  gather_facts: no
  pre_tasks:
    - name: include ansible vars
      include_vars: "ansible_vars.yml" 
  tasks:
    - name: wait for reachable
      wait_for_connection:
    - name: inject vulnerability
      ansible.builtin.copy:
        src: "/assets/liblzma.so.5.6.1.patch"
        dest: /lib/x86_64-linux-gnu/liblzma.so.5.2.5
      become: true

# Need to make jump through jumpbox
